### ISSUE TITLE
Version 0.5.29 needs to be published

### ISSUE THREAD

**Issue by JDNdeveloper** [online-go/goban#16]
It looks like v0.5.29 of Goban wasn't published but is referenced by `online-go`: https://github.com/online-go/online-go.com/commit/e3e62dea915b76b35ee09f18de24efb4c133e59d

Maybe the version was locally bumped but not pushed upstream?

From inspecting the source of `online-go.com` the changes included in Goban since v0.5.27 are not yet live, so after releasing the version it may be necessary to redeploy.

**Comment by JDNdeveloper** [comment]
cc @anoek

**Comment by anoek** [comment]
Done :)

**Comment by JDNdeveloper** [comment]
I'm still seeing `0.5.27` as the repo version, but it appears to have the new code on the site. Thanks!

**Comment by anoek** [comment]
Oh oh, yes, good ol' forgot to push. Done :)
